INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#C79C6E', 'Burglar', 'class_lotro_burglar' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Burglar')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#F58CBA', 'Captain', 'class_lotro_captain' FROM DUAL WHERE (SELECT COUNT(*) FROM `#class_lotro_captain` WHERE `class_name`='Captain')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#ABD473', 'Champion', 'class_lotro_champion' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Champion')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#558A84', 'Guardian', 'class_lotro_guardian' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Guardian')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#ABD473', 'Hunter', 'class_lotro_hunter' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Hunter')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#0070DE', 'Lore-master', 'class_lotro_lore_master' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Lore-master')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#8CA5A3', 'Minstrel', 'class_lotro_minstrel' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Minstrel')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#69CCF0', 'Rune-keeper', 'class_lotro_rune_keeper' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Rune-keeper')=0;
INSERT IGNORE INTO `#__raidplanner_class` (`class_color`, `class_name`, `class_css`) SELECT '#A49900', 'Warden', 'class_lotro_warden' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_class` WHERE `class_name`='Warden')=0;

INSERT IGNORE INTO `#__raidplanner_race` (`race_name`) SELECT 'Race of Man' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_race` WHERE `race_name`='Race of Man')=0;
INSERT IGNORE INTO `#__raidplanner_race` (`race_name`) SELECT 'Hobbit' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_race` WHERE `race_name`='Hobbit')=0;
INSERT IGNORE INTO `#__raidplanner_race` (`race_name`) SELECT 'Elf' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_race` WHERE `race_name`='Elf')=0;
INSERT IGNORE INTO `#__raidplanner_race` (`race_name`) SELECT 'Dwarf' FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_race` WHERE `race_name`='Dwarf')=0;

INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Tank',			'white',	'#93232b',	'black',	'role_tank.png' 		FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Tank')=0;
INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Melee DPS',		'white',	'#a06729',	'black',	'role_melee_dps.png'	FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Melee DPS')=0;
INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Ranged DPS',	'white',	'#2983a0',	'black',	'role_ranged_dps.png'	FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Ranged DPS')=0;
INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Healer',		'white',	'#6aa64d',	'black',	'role_heal.png'			FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Healer')=0;
INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Buffer',		'white',	'#6aa64d',	'black',	'role_buffer.png'		FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Buffer')=0;
INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Crowd Control',	'white',	'#6aa64d',	'black',	'role_cc.png'			FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Crowd Control')=0;
INSERT IGNORE INTO `#__raidplanner_role` (`role_name`, `body_color`, `header_color`, `font_color`, `icon_name`) SELECT 'Debuffer',		'white',	'#6aa64d',	'black',	'role_debuffer.png'		FROM DUAL WHERE (SELECT COUNT(*) FROM `#__raidplanner_role` WHERE `role_name`='Debuffer')=0;
